[profile.default]
src = 'contracts'
out = 'forge-out'
libs = ['lib']
evm_version = 'cancun'
optimizer_runs = 1
via_ir = true
verbosity = 2
ffi = true

[rpc_endpoints]
sepoliaRpc = "https://ethereum-sepolia-rpc.publicnode.com"
